### ISSUE TITLE
Create Mini Project using HTML, CSS, Javascript

### ISSUE THREAD

**Issue by akshayysharma** [akshayysharma/hacktoberfest-2020#1]
Any small projects using HTML, CSS, and Javascript are welcomed

**Comment by akshayysharma** [comment]
labels

**Comment by beasthunter758** [comment]
Can you assign me this?

**Comment by akshayysharma** [comment]
@beasthunter758 please go ahead and submit PR, this repo is open and for learning purpose. Anyone can go ahead and make their contribution. Also before making any contribution please read the docs properly. Cheers

**Comment by lucid-dreem** [comment]
Hey, could you clarify a little more what a 'mini project' means?

**Comment by akshayysharma** [comment]
@lucid-dreem "Mini Project" here refers to all small projects like (Toast Notification, Popup / Moda, Rain effect, Background Change, Dark Mode Toggle, Image Carouse, Sound Board, Zoom effect). These are some ideas, you can go ahead and make projects like these not necessary the above mentioned one.

**Comment by BraydenTW** [comment]
I just added mine :D

**Comment by akshayysharma** [comment]
@BraydenTW merged, great work, and thank you for the wonderful contribution.

**Comment by BraydenTW** [comment]
Thanks!

**Comment by Adityachaturvedi2906** [comment]
Hey! Can you assign me this?

**Comment by akshayysharma** [comment]
> Hey! Can you assign me this?

Please go ahead and submit the PR :smiley:

**Comment by vansh1999** [comment]
would love to contribute on this

**Comment by akshayysharma** [comment]
> would love to contribute on this

Wonderful, I'll wait for your PR :smiley:

**Comment by Shashank024** [comment]
@akshayysharma  I had added my mini-project which I had made using HTML, CSS, and Javascript.

**Comment by Adityachaturvedi2906** [comment]
@akshayysharma  I just added mine PR : )

**Comment by akshayysharma** [comment]
> @akshayysharma I just added mine PR : )

Good Job 😄 , I have merged your PR 👍

**Comment by Adityachaturvedi2906** [comment]
> > @akshayysharma I just added mine PR : )
> 
> Good Job 😄 , I have merged your PR 👍 

Please check it once is it merged properly because its not visible to me

**Comment by asadkhalid305** [comment]
I have raised a PR for project (Todo App) written in Vuejs which uses Vuex (state management) to manage the state of whole application.

**Comment by VicodinAbuser** [comment]
Hey @akshayysharma ! I want to contribute a mini project "Emojipedia" , a kind of an encyclopedia for emojis, made using React.

**Comment by drashtipatel2503** [comment]
Hii, can I try a small layout designing?

**Comment by VicodinAbuser** [comment]
Hi @akshayysharma ! I have made a PR for a mini project made with React - Emojipedia. Please check.

**Comment by akshayysharma** [comment]
> Hii, can I try a small layout designing?

@drashtipatel2503 Yes, Please go ahead and submit the PR

**Comment by akshayysharma** [comment]
> > > @akshayysharma I just added mine PR : )
> > 
> > 
> > Good Job 😄 , I have merged your PR 👍
> 
> Please check it once is it merged properly because its not visible to me

It's merged, kindly check now, I cannot see any open PR from your name!

**Comment by 96RadhikaJadhav** [comment]
Hi @akshayysharma... I have added a color guessing game.. Could you please review my PR once?..Thanks!

**Comment by techyharshit123** [comment]
Hey @akshayysharma, I have added a new game created in HTML,CSS and JS. I hope you'll be reviewing my PR. Please check it once. Thanks!!

**Comment by natzoz** [comment]
Hello @akshayysharma is Java or C also welcome in this issue? May I be assigned to this?

**Comment by Adithanvijayan** [comment]
@akshayysharma I have created a pull request for TicTacToe Game in java

**Comment by akshayysharma** [comment]
> Hello @akshayysharma is Java or C also welcome in this issue? May I be assigned to this?

Hey @natzoz, Yes, in fact, I have created one more issue for that where you can submit code view C, CPP, Java, etc 😄 , Please submit the PR 👍

**Comment by PulsaraSandeepa** [comment]
I would like to contribute to this😊?

**Comment by akshayysharma** [comment]
> I would like to contribute to this😊?

@PulsaraSandeepa , please go ahead and submit the PR 👍

**Comment by srishtij2000** [comment]
Can I contribute by directly submitting a PR?

**Comment by srishtij2000** [comment]
I have submitted a PR so kindly review it.

**Comment by srishtij2000** [comment]
Kindly review my PR

**Comment by srishtij2000** [comment]
I have issued another PR. So kindly review it.

**Comment by hidalgo-vntu** [comment]
would love to contribute

**Comment by Adityachaturvedi2906** [comment]
@akshayysharma I submit my PR, please review it.

**Comment by akshayysharma** [comment]
> would love to contribute

Hi @hidalgo-vntu , Please submit the PR 😄

**Comment by nusart** [comment]
@akshayysharma Please assign me this, would like to contribute

**Comment by akshayysharma** [comment]
> @akshayysharma Please assign me this, would like to contribute

@Nusart, Please submit the PR 👍

**Comment by akshayysharma** [comment]
Closing this Issue, Thanks all for all your wonderful contributions 😄
