### ISSUE TITLE
Hey, can I put my React.js Chat Application here?

### ISSUE THREAD

**Issue by sahilpabale** [akshayysharma/hacktoberfest-2020#12]
I have made a React.js and Firebase backed Chatting Application
So can I add it here for people to contribute

**Comment by akshayysharma** [comment]
Yes, Please submit PR 👍

**Comment by sahilpabale** [comment]
> Yes, Please submit PR 👍

Yeah, will do it

**Comment by sahilpabale** [comment]
So i just need to make a sub repository in the main hacktoberfest-2020 repo right?

**Comment by akshayysharma** [comment]
> So i just need to make a sub repository in the main hacktoberfest-2020 repo right?

I have provided the instructions in the readme file, please check :)
