### ISSUE TITLE
This repository seems to be “ineligible” for Hacktoberfest 2020

### ISSUE THREAD

**Issue by BraydenTW** [akshayysharma/hacktoberfest-2020#3]
I just submitted my PR to add my project “simple-react-crm” to this repository and this error shows up in my Hacktoberfest dashboard:

![](https://iili.io/2W3vaf.jpg)

Will it count towards my 4 PRs? Is there something you can do to fix this?

**Comment by akshayysharma** [comment]
Please check now @BraydenTW

**Comment by BraydenTW** [comment]
Sorry @akshayysharma it still says "ineligible".

**Comment by BraydenTW** [comment]
Never mind, it works now. Just took a minute.

**Comment by akshayysharma** [comment]
@BraydenTW, this happened because HAcktoberfest had made some changes and I was not aware of it. I followed up and hance your changes are visible now :)

**Comment by BraydenTW** [comment]
Thanks for doing this. Just got my 4th pull request :D
