### ISSUE TITLE
Competitive Programming(LeetCode, HackerRank, HackerEarth)

### ISSUE THREAD

**Issue by akshayysharma** [akshayysharma/hacktoberfest-2020#5]
You can submit any competitive program code, language is not a barrier.

**Comment by TicTak21** [comment]
Hi, @akshayysharma.
I created a console application to search for tweets. Can you check my pull request?

**Comment by akshayysharma** [comment]
@TicTak21, Awesome work, I have merged your PR 👍

**Comment by TicTak21** [comment]
Thank you.

**Comment by hacktoberfesttempaccount1234** [comment]
Hi! I'm a beginner to Github and Hacktoberfest, let me know if I submitted PR correctly? Thanks! Tried to add some leetcode october challenge solution (https://leetcode.com/explore/challenge/card/october-leetcoding-challenge/561/week-3-october-15th-october-21st/)

**Comment by atharvakarnik** [comment]
Hey @akshayysharma, I would like to contribute to this repository... Can you please assign me? I will be using Python...

**Comment by akshayysharma** [comment]
@atharvakarnik, please go ahead and submit the PR.

**Comment by shristabaruah** [comment]
hi, @akshayysharma I would like to contribute to this  repository .I will be using java.Can you please assign me?

**Comment by akshayysharma** [comment]
> hi, @akshayysharma I would like to contribute to this repository .I will be using java.Can you please assign me?

@shristabaruah, Please go ahead and submit the PR :smiley:

**Comment by varishtsg** [comment]
I wanted to add code for LRU cache can I go ahead? @akshayysharma

**Comment by akshayysharma** [comment]
> I wanted to add code for LRU cache can I go ahead? @akshayysharma

Yes Please :smiley:

**Comment by Muskan33** [comment]
Hey, @akshayysharma I would like to contribute. Can you please assign me this repo? I will be using C++.

**Comment by akshayysharma** [comment]
> Hey, @akshayysharma I would like to contribute. Can you please assign me this repo? I will be using C++.

@Muskan33, Please go ahead and submit the PR :smiley:

**Comment by rahul975337** [comment]
please check my pr

**Comment by akshayysharma** [comment]
> Hi! I'm a beginner to Github and Hacktoberfest, let me know if I submitted PR correctly? Thanks! Tried to add some leetcode october challenge solution (https://leetcode.com/explore/challenge/card/october-leetcoding-challenge/561/week-3-october-15th-october-21st/)

Great Job 😄

**Comment by khandelwal20sid** [comment]
I've submitted my PR with a dynamic table layout using HTML, CSS and Js

**Comment by I3han** [comment]
Hey can I contribute to this

**Comment by akshayysharma** [comment]
> Hey can I contribute to this

@I3han, Yes please go ahead 😄

**Comment by VicodinAbuser** [comment]
@akshayysharma  I would like to add a solution to an interesting problem on Hacker Rank - Repetitive K-Sums - in Python. Can you assign me?

**Comment by akshayysharma** [comment]
> @akshayysharma I would like to add a solution to an interesting problem on Hacker Rank - Repetitive K-Sums - in Python. Can you assign me?

@VicodinAbuser, please go ahead and submit the PR 😄

**Comment by VicodinAbuser** [comment]
@akshayysharma Submitted the PR. Please check.

**Comment by PulsaraSandeepa** [comment]
Hey, Can I contribute to this?

**Comment by akshayysharma** [comment]
> Hey, Can I contribute to this?

Yes Please 🚀

**Comment by Yash-Vijayvargiya** [comment]
@akshayysharma I would like to add a solution to an interesting problem on LeetCode - String to Integer (atoi) - in C++. Can you assign me?

**Comment by akshayysharma** [comment]
> @akshayysharma I would like to add a solution to an interesting problem on LeetCode - String to Integer (atoi) - in C++. Can you assign me?

Please go ahead and submit the PR 😄

**Comment by Yash-Vijayvargiya** [comment]
@akshayysharma I had  submitted PR, please review it.

**Comment by aansari4599** [comment]
hi @akshayysharma i would like to contribute to this repository. Can you please assign me? I will be using C++.

**Comment by akshayysharma** [comment]
> hi @akshayysharma i would like to contribute to this repository. Can you please assign me? I will be using C++.

Hey @aansari4599, sure, please submit the PR 😄

**Comment by aansari4599** [comment]
@akshayysharma I have submitted the PR #79 . Please check  it.

Thanks !

**Comment by Yash-Vijayvargiya** [comment]
@akshayysharma  sir, can I add more solution of  leetcode problem.

**Comment by akshayysharma** [comment]
> @akshayysharma sir, can I add more solution of leetcode problem.

@Yash-Vijayvargiya , yes please 😄

**Comment by aansari4599** [comment]
@akshayysharma I resubmitted PR #79 with the changes you suggested. Please Check it.

Thanks !

**Comment by Yash-Vijayvargiya** [comment]
@akshayysharma  I have submitted the PR #83 . Please check it.

**Comment by hacktoberfesttempaccount1234** [comment]
Hi! I added some more daily challenge solutions in #84 and #85

**Comment by akshayysharma** [comment]
Closing this issue, thanks all for your wonderful contributions 😄
